version: '2'

services:
  # sidebar:
    # image: eddielo/sidebar:latest
    # build: sidebar/
    # depends_on:
    #   - 'database'
    # ports: 
    #   - '80:7878'
    # container_name: sidebar

  proxy:
    build: .
    ports: 
      - '8080:8080'
    container_name: proxy

  # seed:
  #   # image: eddielo/seed:latest
  #   build: sidebar/database
  #   depends_on:
  #     - 'database'
  #   ports: 
  #     - '3000:3000'
  #   container_name: seed

  # database:
  #   image: mysql:5.7.23
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: nopass
  #     MYSQL_DATABASE: YelpReactorSidebar
  #   ports:
  #     - "3306:3306"
  #   container_name: database
